### ISSUE TITLE
Unreachable IPs in MD5 in TLS Certificate Signature (Test 10)

### ISSUE THREAD

**Issue by rdrgporto** [3CORESec/testmynids.org#1]
Hi, 

First of all, thank you very much for this tool 😄.

Secondly, when I launch **MD5 in TLS Certificate Signature (Test 10)**, it stucks. I have taken a quick look at your script (**tmNIDS**) in order to find out what this test does.

```
test_md5rsa () {
  # This test is made possible by Barracuda, as they still believe MD5 in certificates is OK
  for ip in 64.235.158.{25..30}
    do
      echo Q | openssl s_client -connect ${ip}:443 -tls1 > /dev/null 2>&1
    done
}
````

I have used several commands, for example: **nc** or **ping** and it seems to be that these **IPs range** are not reachable.

Thanks in advance,

Regards

**Comment by 0xtf** [comment]
Hi @rdrgporto, thanks for bringing this to our attention. 

The comment on that test hints at what possibly might have happened 😉 It seems Barracuda updated their endpoints and is no longer using these IPs. 

I'll see if we can find other endpoints that still utilize MD5. If we can't find it we'll just remove T10 from the script.

We'll update this issue ASAP.

**Comment by 0xtf** [comment]
I've committed https://github.com/3CORESec/testmynids.org/commit/34b66d1fa8172bdcb58e43ffed17ef2b233c5f2a. I'm not sure an alert will fire with that certificate, but at least it won't break execution. 

If you don't mind trying and let us know I'd appreciate the feedback. Otherwise, we'll test detection using the badssl.com host in the upcoming days. 

I think it's better to use a host developed specifically for this (like badssl) than to find a random IP online that still relies on MD5 but will eventually just be decommissioned or updated. 

I'll leave this issue open until we're sure we can trigger T10.

**Comment by 0xtf** [comment]
Seems even badssl.com doesn't have this test working. We'll keep looking.

**Comment by rdrgporto** [comment]
Hi, @0xtf 

Any updates?

Thanks in advance 😃 

Regards

**Comment by 0xtf** [comment]
Hi @rdrgporto, sorry for the delay. 

We couldn't find a stable enough website to put as part of the test. Seeing as the detection was being done from TLS, we wanted to maintain that as part of T10, so we've changed it in https://github.com/3CORESec/testmynids.org/commit/44f81323736e36a676a04196c3429da914eaf13d so that it fires off a TLS signature (as well as a DNS one) related to the usage of an anonymous filesharing website. 

This way we still have a cool detection and we maintain the original protocol coverage.

**Comment by rdrgporto** [comment]
Hi, @0xtf 

Thank you very much 😃.

Regards

**Comment by 0xtf** [comment]
No problem @rdrgporto! Thanks for reaching out. If you have any ideas for additional tests feel free to let us know. 👍🏼
